---
- name: Ping ESXi hosts
  hosts: all
  gather_facts: no # We don't need to gather facts for a simple ping, speeds up execution
  connection: smart # This is usually the default, but good to be explicit
  # You might need to specify ansible_python_interpreter if it's not found automatically,
  # but for ESXi's minimal Python, it usually works fine.
  # ansible_python_interpreter: /usr/bin/python

  tasks:
    - name: Test connectivity to ESXi hosts
      ansible.builtin.ping:
